apiVersion: v1
kind: Pod
metadata:
  name: gold-bar
  namespace: fort-knox
spec:
  serviceAccountName: your-service-account-name  # Replace with the actual Service Account name
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    allowPrivilegeEscalation: false
  containers:
  - name: bullion
    image: busybox:1.34.0
    command: ["sh", "-c"]
    args: ["sleep 1h"]

