apiVersion: v1
kind: Pod
metadata:
  name: gold-bar
  namespace: fort-knox
spec:
  serviceAccountName: gold-bar-sa
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    allowPrivilegeEscalation: false
  containers:
    - name: bullion
      image: busybox:1.34.0
      command: ["sh", "-c", "sleep 1h"]

