winston_churchill_quotes = [
    "If you are going through hell, keep going",
    "Never, never, never give up.",
    "Time and money are largely interchangeable terms.",
    "Personally I'm always ready to learn, although I do not always like being taught.",
    "Vengeance is the most costly and dissipating of luxuries.",
    "Harsh laws are at times better than no laws at all.",
    "Everyone has his day, and some days last longer than others.",
    "Success is not final, failure is not fatal, it is the courage to continue that counts.",
    "It is not in our power to anticipate our destiny.",
    "All the greatest things are simple, and many can be expressed in a single word: freedom; justice; honor; duty; mercy; hope.",
    "Nothing in life is so exhilarating as to be shot at without result.",
    "My tastes are simple: I am easily satisfied with the best.",
    "To improve is to change, so to be perfect is to change often.",
    "All wisdom is not new wisdom.",
    "Every man should ask himself each day whether he is not too readily accepting negative solutions.",
    "If you destroy a free market you create a black market.",
    "The price of greatness is responsibility.",
    "All I can say is that I have taken more out of alcohol than alcohol has taken out of me.",
    "“I like pigs. Dogs look up to us. Cats look down on us. Pigs treat us as equals.",
    "When the eagles are silent, the parrots begin to jabber.",
    "In finance, everything that is agreeable is unsound and everything that is sound is disagreeable.",
    "You have enemies? Good. That means you've stood up for something in your life.",
    "The greatest lesson in life is to know that even fools are right sometimes.",
    "The farther backward you can look, the farther forward you are likely to see.",
    "One ought to be just before one is generous.",
    "To build may have to be the slow and laborious task of years. To destroy can be the thoughtless act of a single day.",
    "It is wonderful what great strides can be made when there is a resolute purpose behind them.",
    "Out of intense complexities, intense simplicities emerge.",
    "Courage is what it takes to stand up and speak, it’s also what it takes to sit down and listen.",
    "If you have an important point to make, don’t try to be subtle or clever. Use a pile driver. Hit the point once. Then come back and hit it again. Then hit it a third time—a tremendous whack.",
    "We make a living by what we get, but we make a life by what we give.",
    "I never worry about action, but only about inaction.",
    "War never pays its dividends in cash on the money it costs.",
    "Continuous effort—not strength or intelligence—is the key to unlocking our potential.",
    "Courage is rightly esteemed the first of human qualities because it has been said, it is the quality which guarantees all others.",
    "Nothing makes a man more reverent than a library.",
    "You will never get to the end of the journey if you stop to shy a stone at every dog that barks.",
    "For myself I am an optimist—it does not seem to be much use being anything else.",
    "The nose of the bulldog has been slanted backwards so that he can breathe without letting go.",
    "One always measures friendships by how they show up in bad weather.",
    "There are a terrible lot of lies going about the world, and the worst of it is that half of them are true.",
    "You must look at facts because they look at you.",
    "The empires of the future are the empires of the mind.",
    "We have a lot of anxieties, and one cancels out another.",
    "Nourish your hopes, but do not overlook realities.",
    "To be really happy and really safe, one ought to have at least two or three hobbies, and they must all be real.",
    "History will be kind to me for I intend to write it.",
    "It is a mistake to try to look too far ahead. The chain of destiny can only be grasped one link at a time.",
    "Attitude is a little thing that makes a big difference.",
    "Craft is common both to skill and deceit.",
    "In a war, you can only be killed once, but in politics, many times.",
    "It’s not enough that we do our best; sometimes we have to do what’s required.",
    "Evils can be created much quicker than they can be cured.",
    "Give us the tools, and we will finish the job.",
    "Those who can win a war well can rarely make a good peace, and those who could make a good peace would never have won the war.",
    "Broadly speaking short words are best and the old words when short, are best of all.",
    "We shape our dwellings, and afterwards our dwellings shape us.",
    "Success is the ability to go from one failure to another with no loss of enthusiasm.",
    "There is only one duty, only one safe course, and that is to try to be right and not to fear to do or say what you believe to be right.",
    "What is adequacy? Adequacy is no standard at all.",
    "In the course of my life I have often had to eat my words, and I must confess that I have always found it a wholesome diet.",
    "It is the time to dare and endure.",
    "If we open a quarrel between the past and the present we shall find that we have lost the future.",
    "Politics is the ability to foretell what is going to happen tomorrow, next week, next month and next year. And to have the ability afterwards to explain why it didn’t happen.",
    "It is better to be making the news than taking it; to be an actor rather than a critic.",
    "I have in my life concentrated more on self-expression than self-denial.",
    "There are a terrible lot of lies going about the world, and the worst of it is that half of them are true.",
    "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
    "There is always much to be said for not attempting more than you can do and for making a certainty of what you try. But this principle, like others in life and war, has its exceptions.",
    "The true guide of life is to do what is right.",
    "Tact is the ability to tell someone to go to hell in such a way that they look forward to the trip.",
    "You never can tell whether bad luck may not after all turn out to be good luck.",
    "You must put your head into the lion’s mouth if the performance is to be a success.",
    "Men occasionally stumble over the truth, but most of them pick themselves up and hurry off as if nothing ever happened.",
    "Politics is not a game. It is an earnest business.",
    "I like things to happen, and if they don’t happen I like to make them happen.",
    "An appeaser is one who feeds a crocodile—hoping it will eat him last.",
    "The power of man has grown in every sphere, except over himself.",
    "Without a measureless and perpetual uncertainty, the drama of human life would be destroyed.",
    "I am never going to have anything more to do with politics or politicians. When this war is over I shall confine myself entirely to writing and painting.",
    "The truth is incontrovertible. Malice may attack it, ignorance may deride it, but in the end, there it is.",
    "I may be drunk Miss, but in the morning I will be sober and you will still be ugly.",
    "I object on principle to doing by legislation what properly belongs to human good feeling and charity.",
    "Every day you may make progress. Every step may be fruitful. Yet there will stretch out before you an ever-lengthening, ever-ascending, ever-improving path. You know you will never get to the end of the journey. But this, so far from discouraging, only adds to the joy and glory of the climb.",
    "Difficulties mastered are opportunities won.",
    "The pessimist sees difficulty in every opportunity. The optimist sees the opportunity in every difficulty.",
    "The first duty of the university is to teach wisdom, not a trade; character, not technicalities. We want a lot of engineers in the modern world, but we do not want a world of engineers.",
    "The English never draw a line without blurring it.",
    "You cannot cure cancer by a majority.",
    "If we win, nobody will care. If we lose, there will be nobody to care.",
    "The best argument against democracy is a five-minute conversation with the average voter.",
    "We shall show mercy, but we shall not ask for it.",
    "We must beware of needless innovation, especially when guided by logic.",
    "If you have ten thousand regulations you destroy all respect for the law.",
    "We are masters of the unsaid words, but slaves of those we let slip out.",
    "Do not let spacious plans for a new world divert your energies from saving what is left of the old.",
    "There is no time for ease and comfort. It is time to dare and endure.",
    "Solitary trees, if they grow at all, grow strong.",
    "I'm prepared to meet my Maker. Whether my Maker is prepared for the great ordeal of meeting me is another matter.",
    "We are stripped bare by the curse of plenty.",
    "A lie gets halfway around the world before the truth has a chance to get its pants on."
]

